<?php

namespace Repository;

/**
 * PanelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllActivePanel()
    {
    	$query = "	SELECT p 
    				FROM Entity\Panel p
    				WHERE p.status IS NULL
    				ORDER BY p.position ASC";

        return $this->getEntityManager()
        			->createQuery($query)
        			->getResult();
    }
}
